name: 'Test'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Convert nbt to mcstructure
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: python __main__.py
      - uses: actions/upload-artifact@v3
        with:
          name: structures
          path: ./structures
